[project]
name = "trn"
version = "0.1.12"
description = "CLI tool to translate text with LLMs"
authors = [
  { name="Alexander Ryabov", email="alex.ryabov@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "configargparse>=1.7.5",
    "curl-cffi>=0.15.0",
    "html2text>=2025.4.15",
    "llm>=0.31",
    "llm-anthropic>=0.25",
    "llm-gemini>=0.32",
    "pyperclip>=1.11.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[dependency-groups]
dev = [
  "isort",
  "pre-commit",
  "pytest",
  "pytest-xdist",
  "ruff",
  "safety",
  "ty",
]
[project.scripts]
trn = "trn:main"

[tool.uv]
package = true

[project.urls]
Homepage = "https://github.com/haron/trn"
Issues = "https://github.com/haron/trn/issues"

[tool.ty.rules]
unknown-argument = "ignore"

[tool.pytest.ini_options]
addopts = "--show-capture=log --exitfirst --maxfail=1"

[tool.ruff.lint]
ignore = ["F401", "E402"]

[tool.ruff]
line-length = 140

[tool.ty.src]
respect-ignore-files = true
